### ISSUE TITLE
ESP32 

### ISSUE THREAD

**Issue by arnold-b** [ploys/arduino-goodix#2]
Hey, 

thanks for your work. 
I just now try to get it running with ESP32 Arduino. 

The I2C communication is ok, but gt911 don´t send int when it is press. but sometimes he send a lot int without different data. 

i don´t know where i should start to search ?. 

what´s going on with your firmware file. do i need this ?

thanks arnold

**Comment by nik-sharky** [comment]
Try to check power stability and pins connection first. It is most common problem.

**Comment by Staars** [comment]
Hi,
I also did not get it to work on ESP32, which of course might be related to power/connection issues.
At least I could get a reaction from the board via i2cscan example.

At the moment I only like to know, on which specific hardware you tested your project?

**Comment by arnold-b** [comment]
Hello Christian, 

 

i use NODEMCU 32 with Wroom32 

 

I2C Scan works and I can read I2C Data

 

Be car full. There is a BUG in the current library for Arduino ESP32. 

 

 <https://github.com/arnold-b> @arnold-b the best working files are in this repo. Between RC1 and Release 1.0.0 there were multiple changes to I2C, Between RC4 and Release 1.0.0 I resolved a problem with interrupt saturation. During this major rewrite, I made a mistake. It manifested when using a Write ReSTART operation. (Wire.endTransmission(false);) as you noticed, the subsequent Read operation does not return any data.

just follow the instruction in  <https://github.com/espressif/arduino-esp32/issues/1962> #1962, copy the four files from this repo. replace the four same your Arduino installation with those file.

*	\cores\esp32\esp32-hal-i2c.h
*	\cores\esp32\esp32-hal-i2c.c
*	\libraries\Wire\src\Wire.h
*	\libraries\Wire\src\Wire.cpp

 

 

Von: Christian <notifications@github.com> 
Gesendet: Montag, 26. November 2018 18:25
An: ploys/arduino-goodix <arduino-goodix@noreply.github.com>
Cc: arnold-b <arnold.braun@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [ploys/arduino-goodix] ESP32 (#2)

 

Hi,
I also did not get it to work on ESP32, which of course might be related to power/connection issues.
At least I could get a reaction from the board via i2cscan example.

At the moment I only like to know, on which specific hardware you tested your project?

**Comment by Staars** [comment]
Hi,

Thanks for the info.
I consider ESP32 with Arduino as a moving target (to say the least) and had problems in other areas (Wifi+BT and I2C too). So I start to believe, that Arduino will not be as stable as on the „older“ platforms for a very long time (or longer;).
Maybe I try to port this to ESP-IDF, but I still do not know, if I even have non-defective hardware.
@ploys What board did You use?

**Comment by arnold-b** [comment]
Hi,

 

i´m playing around with ESP a long time. 

 

When esp32 are new on the market. And I have to say to use eclipse is  more reliable as Arduino ESP.

 

Von: Christian <notifications@github.com> 
Gesendet: Dienstag, 27. November 2018 00:16
An: ploys/arduino-goodix <arduino-goodix@noreply.github.com>
Cc: arnold-b <arnold.braun@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ploys/arduino-goodix] ESP32 (#2)

 

Hi,

Thanks for the info.
I consider ESP32 with Arduino as a moving target (to say the least) and had problems in other areas (Wifi+BT and I2C too). So I start to believe, that Arduino will not be as stable as on the „older“ platforms for a very long time (or longer;).
Maybe I try to port this to ESP-IDF, but I still do not know, if I even have non-defective hardware.
@ploys What board did You use?

**Comment by arnold-b** [comment]
The right one on the pic is Wroom32. 

In one month I have my own small board and then I can also debug over jtag. 

 

My current Jlink don’t work with esp32. 

 

Von: Christian <notifications@github.com> 
Gesendet: Dienstag, 27. November 2018 00:16
An: ploys/arduino-goodix <arduino-goodix@noreply.github.com>
Cc: arnold-b <arnold.braun@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ploys/arduino-goodix] ESP32 (#2)

 

Hi,

Thanks for the info.
I consider ESP32 with Arduino as a moving target (to say the least) and had problems in other areas (Wifi+BT and I2C too). So I start to believe, that Arduino will not be as stable as on the „older“ platforms for a very long time (or longer;).
Maybe I try to port this to ESP-IDF, but I still do not know, if I even have non-defective hardware.
@ploys What board did You use?

**Comment by nik-sharky** [comment]
@ploys What board did You use?
I used Wemos ESP8266

**Comment by arnold-b** [comment]
I use ESP-WROOM-32

 https://www.digikey.de/product-detail/de/schtoeta-engineering-limited/ESP32-DEVKITC-32D/1965-1000-ND/9356990?utm_adgroup=RF+Evaluation+and+Development+Kits&mkwid=sX3B9iiRl&pcrid=218206583410&pkw=&pmt=&pdv=c&productid=9356990&slid=&gclid=EAIaIQobChMIydqL2e703gIVReR3Ch1x7g--EAQYASABEgL5C_D_BwE


Von: Nik <notifications@github.com> 
Gesendet: Dienstag, 27. November 2018 14:37
An: ploys/arduino-goodix <arduino-goodix@noreply.github.com>
Cc: arnold-b <arnold.braun@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ploys/arduino-goodix] ESP32 (#2)

 

@ploys <https://github.com/ploys>  What board did You use?
I used Wemos ESP8266

**Comment by Staars** [comment]
> @ploys What board did You use?
> I used Wemos ESP8266

Then I fear that I have hardware problem, because that did not work either.
Anyway, thank you for your answers.

**Comment by nik-sharky** [comment]
@Staars If You guess that problem is in hardware, try to check that You can read something from GT chip or any other via i2c. Also check pull-up resistors and chip connection (I use FPC adapter pcb and sometimes fpc cable twists in joint).

**Comment by Staars** [comment]
I will put my ESP32-efforts on hold and continue with the ESP8266.
Until now, I could communicate via I2C in a limited way. 
That means in the usual i2c-scanner-approach I got no error when writing "7-bit-address plus W-Bit" to the device (using ESP-idf).
I could read a bunch of bytes from the device (i.e. the config from 0x8047 and upwards) without an error message, but the result was garbage (mostly 0xff's).

But as I know now, that it should be possible with the 8266, I already tried it out and made some observations, but this belongs to another thread.

**Comment by Staars** [comment]
At least to some degree I can conclude, that most of my tries with the ESP32 could not work, because of insufficient power. In my now fully working ESP8266-setup I had to use a powered USB-switch. 🤦‍♂️

**Comment by nik-sharky** [comment]
So my first guess "Try to check power stability" was right? :)

**Comment by Staars** [comment]
Yes, this always right ;)

**Comment by Staars** [comment]
So, I am nearly there on the ESP32.
I have continued to port it to ESP-idf and most of the stuff is running. There is still some sort of a padding problem, but I hope to get around this. Besides that I can enjoy a fast and stable operation.

`C0: #0 3330,5121 s:0
C1: #2 8449,0 s:1026
C2: #1 0,22787 s:57345
C3: #0 28932,5376 s:12033
C4: #12 2348,16397 s:5`

**Comment by Staars** [comment]
YES!!

#pragma pack(1) did the trick.

**Comment by nik-sharky** [comment]
Coordinates looks incorrect C2: #id x,y s:pressure, can be mistake in my lib, will try to check on next week on my device.

**Comment by nik-sharky** [comment]
Which chip You use? GT911?

**Comment by Staars** [comment]
Yes, but now all is okay. I am quite shure, that this is a padding problem of the structs. At least I could solve it with the above mentioned `#pragma pack(1)`.
What I should mention is, that I use PlatformIO and not the Arduino-IDE. Maybe only there the pragma setting is needed(?).
For the ESP32 I switched to ESP-IDF and started a repo on my github-account (still in a very rough state). Since then the ESP32 is rock stable with my no-name touch-board.

Thanks a lot for your help! 👍

**Comment by nik-sharky** [comment]
You are welcome
