### ISSUE TITLE
Doesn't work with avr Arduinos Such as Uno

### ISSUE THREAD

**Issue by Mobin-Mortazavi** [ploys/arduino-goodix#8]
Bro , First thanks for sharing your lib

but I can't make it work with Uno

I get some errors about godix::armIRQ ......

Can u help?

**Comment by nik-sharky** [comment]
Same problem as in issue#7

On arduino there is no ICACHE_RAM_ATTR macro, initially library was developed for ESP8266.
Try to define macro in code or remove it from Goodix.cpp.

Will fix it later.

**Comment by Mobin-Mortazavi** [comment]
Yes, I know, But I still have other Errors, Can u please check it?

**Comment by Mobin-Mortazavi** [comment]
libraries\arduino-goodix-master\Goodix.cpp.o (symbol from plugin): In function `_goodix_irq_handler()':

(.text+0x0): multiple definition of `_log_printf(char const*, ...)'

sketch\GT911_touch.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by mj-km** [comment]
Thank you for sharing your library!

However, I am also getting the same error as posted by Mobin.

Has this issue been solved?

**Comment by hadiinfo** [comment]
Hi Mobin, mj-km and nik, 

 Is there a resolution to this problem? I have similar issue.

**Comment by nik-sharky** [comment]
Hi all, 

I fix compilation issues for AVR boards, update library and try to compile now.
For AVR boards use GT911_avr_touch example.

**Comment by hadiinfo** [comment]
Thank you so much Nik. This now works. 
I wanted to collaborate with you on something similar in case you are interested. Could you please email me at hadiinfo@gmail.com ?
